### ISSUE TITLE
Markdown parsed

### ISSUE THREAD

**Issue by alorma** [PDDStudio/highlightjs-android#1]
Hi.

Is there any way to load a markdown file and show it parsed?

instead of:

`**Hello**`

**Hello**

**Comment by PDDStudio** [comment]
Hey @alorma,

This library is supposed to show the _highlighted syntax_ of a file.
So this is absolutely normal that your markdown doesn't get parsed.
In your case I'd recommend you for displaying a correct markdown file (not the syntax itself) to use a [MarkdownView for Android](https://github.com/falnatsheh/MarkdownView) (or any similar library)

Regards

**Comment by alorma** [comment]
I will try, thanks
