### ISSUE TITLE
PHP file not parsed correct

### ISSUE THREAD

**Issue by alorma** [PDDStudio/highlightjs-android#2]
Hi.

I'm using this library in Gitskarios app, and i this file looks is not well parsed:

https://github.com/TextControl/txtextcontrol-reportingcloud-php/blob/master/src/Filter/DateTimeToTimestamp.php

![](https://s3.amazonaws.com/o3cxerf5/Public/jwpsh5kh/20160617060354.png)

I've checked, and after removing the `<?php` it loads all the content:

https://github.com/gitskarios/test_readme/blob/master/Test.php

![](https://i.imgur.com/7UqS46e.png)

**Comment by GeorgeWL** [comment]
I'd say this is a pretty key issue btw :+1:

**Comment by PDDStudio** [comment]
Thanks for reporting @alorma 
How are you loading the source into the view? (String, File or URL)
Then I'll see whether I can reproduce this issue

**Comment by alorma** [comment]
It's from a String

**Comment by alorma** [comment]
https://github.com/gitskarios/Gitskarios/blob/develop/app/src/main/java/com/alorma/github/ui/fragment/FileFragment.java#L117

**Comment by PDDStudio** [comment]
Alright, and the language is set to `AUTO_DETECT` ?

**Comment by alorma** [comment]
Yes, you can see in the same file

**Comment by PDDStudio** [comment]
Same here. See #3 for details.

**Comment by PDDStudio** [comment]
Should be fixed with [Version 1.2.0](https://github.com/PDDStudio/highlightjs-android/releases/tag/1.2.0)
