### ISSUE TITLE
Zoom controls don't work

### ISSUE THREAD

**Issue by alorma** [PDDStudio/highlightjs-android#4]
As requested in https://github.com/gitskarios/Gitskarios/issues/478

I did the following:

https://github.com/gitskarios/Gitskarios/blob/develop/app/src/main/java/com/alorma/github/ui/fragment/FileFragment.java#L91

``` java
 @Override
  public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);

    webView = (HighlightJsView) view.findViewById(R.id.webview);

    webView.setTheme(Theme.ANDROID_STUDIO);
    webView.setHighlightLanguage(Language.AUTO_DETECT);
    webView.invokeZoomPicker();
}
```

But nothing appears on the screen

PS: neither work `.zoomIn()` or `.zoomOut()`

**Comment by PDDStudio** [comment]
This was disabled by default.
With [Version 1.1.0](https://github.com/PDDStudio/highlightjs-android/releases/tag/1.1.0) you can enable zoom controls by calling `setZoomSupportEnabled(boolean supportZoom)` on `HighlightJsView`

**Comment by alorma** [comment]
Thanks! Working!
