### ISSUE TITLE
XML files not displayed

### ISSUE THREAD

**Issue by alorma** [PDDStudio/highlightjs-android#5]
This file:

https://github.com/alorma/TestCreateFiles/blob/master/test.xml

``` xml
<root>
<test>
aaa
</test>
<test>
bbb
<test2>
</test2>
bbb
</test>
</root>
```

Is not parsed correctly, even if i set language as XML.

![device-2016-07-08-202043](https://cloud.githubusercontent.com/assets/887462/16697362/9f77ee6a-4549-11e6-8dbf-03df075f5f4d.png)

Refrence: https://github.com/gitskarios/Gitskarios/issues/490

PS: Tested on your example app also

**Comment by PDDStudio** [comment]
Should be fixed with [Version 1.2.0](https://github.com/PDDStudio/highlightjs-android/releases/tag/1.2.0)
