### ISSUE TITLE
Detect when the code loads

### ISSUE THREAD

**Issue by kal27** [PDDStudio/highlightjs-android#7]
How could I detect whether the code was loaded? I am trying to open large files and it takes couple seconds to load the code and display it in the layout.
Is there a way I could detect when the code has been displayed so I can display/hide a progressbar?

Thanks

**Comment by PDDStudio** [comment]
@kal27 you can attach an `OnContentChangedListener` to your `HighlightJsView` via `setOnContentChangedListener()`

The Listener gets called once the new data is loaded and rendered completely.
